version: '3.8'

services:
  # Django Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: stock_insights_backend
    env_file:
      - .env.local
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    volumes:
      - ./backend:/app
    user: root  # Temporary: Run as root to avoid SQLite permission issues
    command: >
      sh -c "
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        python manage.py runserver 0.0.0.0:8000
      "

  # Angular Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: stock_insights_frontend
    env_file:
      - .env.local
    ports:
      - "${FRONTEND_PORT:-4200}:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    command: npm run dev -- --host 0.0.0.0 --port 4200

  # # PostgreSQL Database
  # postgres:
  #   image: postgres:15-alpine
  #   container_name: stock_insights_postgres
  #   env_file:
  #     - .env.local
  #   environment:
  #     POSTGRES_HOST_AUTH_METHOD: trust
  #   ports:
  #     - "${POSTGRES_PORT:-5432}:5432"